[workspace]
resolver = "3"
members = ["crates/svd-lint-core", "crates/svd-lint-cli"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
svd-lint-core = { path = "crates/svd-lint-core" }

svd-parser = "0.14"
roxmltree = "0.21"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
miette = { version = "7", features = ["fancy"] }

insta = { version = "1", features = ["filters"] }
assert_cmd = "2"
predicates = "3"
tempfile = "3"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "symbols"
debug = false
